// ---------------------------------------------------------------------------
// Cross-repo NDJSON integration regression.
//
// Ties OUR emulator's audio-regression scenarios to HER renderer. Each golden
// fixture under test/fixtures/ is a deterministic capture of the emulator's
// NDJSON stream (snapshot + reconcile + per-turn state_change/animation/outcome)
// for a typed bmw_new signature — generated by the assistant repo's
// tools/ui/gen_golden_ndjson.sh (see test/fixtures/README.md). This test replays
// each through bmwRenderer.ingest() and asserts:
//   (a) ZERO error-level console output (the renderer never red-errors an
//       expected event or outcome), and
//   (b) the UI state reflects the command (the subsystem's field changed).
//
// This is the durable instrument: a taxonomy/format/enum drift between our emit
// and her mapping can no longer silently return — it trips here.
//
// Regenerate fixtures after an emulator emit change:
//   (in Liquid4All/assistant) tools/ui/gen_golden_ndjson.sh \
//       /path/to/automotive-demo/test/fixtures
// ---------------------------------------------------------------------------
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect, beforeEach } from "vitest";
import { ingest, reset, getMirror } from "../src/agent/bmwRenderer";
import { getState } from "../src/state/vehicleState";
import { getMusic } from "../src/state/musicStore";
import { getAgentState, clearConsole } from "../src/agent/agentStore";

/** Replay one golden fixture through the renderer from a clean slate. */
function replay(fixture: string): void {
  reset();
  clearConsole();
  const text = readFileSync(
    resolve(__dirname, "fixtures", `${fixture}.ndjson`),
    "utf8",
  );
  for (const line of text.split(/\r?\n/)) {
    if (line.trim()) ingest(line);
  }
}

/** The error-level console lines the renderer emitted for the last replay. */
function errorLines(): string[] {
  return getAgentState()
    .consoleLog.filter((e) => e.level === "error")
    .map((e) => e.text);
}

/** Non-error console lines (an EXPECTED event/outcome is surfaced, not dropped). */
function surfacedLines(): string[] {
  return getAgentState()
    .consoleLog.filter((e) => e.level !== "error")
    .map((e) => e.text);
}

interface Scenario {
  /** Fixture basename under test/fixtures/ (without .ndjson). */
  fixture: string;
  /** Assert her UI state reflects the command. Runs after a clean replay. */
  reflects: () => void;
}

// One entry per subsystem her UI renders (climate, media, lighting) plus the
// console-only subsystems (windows, drive, nav, ambient) and the gated outcomes
// (not_equipped / not_implemented). Every scenario ALSO asserts zero error spew.
const SCENARIOS: Scenario[] = [
  {
    fixture: "climate_temp",
    reflects: () => expect(getState().temperature).toBe(71),
  },
  {
    fixture: "climate_fan",
    reflects: () => expect(getState().fan).toBe(true),
  },
  {
    fixture: "climate_ac",
    reflects: () => expect(getState().climate).toBe("ac"),
  },
  {
    fixture: "climate_auto",
    reflects: () => expect(getState().climate).toBe("auto"),
  },
  {
    fixture: "climate_seat_heat",
    reflects: () => expect(getState().seatHeat.driver).toBe(3),
  },
  {
    fixture: "media_mute",
    reflects: () => expect(getMusic().volume).toBe(0),
  },
  {
    fixture: "media_volume",
    // reconcile seeds volume 20 (unmuted); INCREASE → 30.
    reflects: () => expect(getMusic().volume).toBe(30),
  },
  {
    fixture: "media_source",
    reflects: () => {
      expect(getMirror()["media.source"]).toBe("SPOTIFY");
      expect(getMusic().playing).toBe(true);
    },
  },
  {
    fixture: "media_track",
    // media_skip NEXT steps track_index 0 → 1.
    reflects: () => expect(getMusic().index).toBe(1),
  },
  {
    fixture: "lighting",
    reflects: () => expect(getState().headlights).toBe("on"),
  },
  {
    fixture: "windows",
    // No web-rig geometry for windows yet — surfaced in the mirror + console
    // (info-level), never dropped. Reflection = the mirror tracked it.
    reflects: () => expect(getMirror()["body.window.DRIVER"]).toBe("OPEN"),
  },
  {
    fixture: "drive_mode",
    reflects: () => expect(getMirror()["drive.mode"]).toBe("SPORT"),
  },
  {
    fixture: "nav",
    reflects: () =>
      expect(getMirror()["nav.destination"]).toBe("Blue Bottle Coffee"),
  },
  {
    fixture: "ambient",
    reflects: () => expect(getMirror()["lighting.ambient_color"]).toBe("RED"),
  },
  {
    fixture: "blinds_not_equipped",
    // Capability-gated on the 330i base trim: a valid call, no state change, a
    // not_equipped outcome. Must NOT red-error (it is an expected product state);
    // the outcome is still SURFACED in the console at info level, not dropped.
    reflects: () =>
      expect(
        surfacedLines().some((t) => /car_adjust_blind.*not equipped/.test(t)),
      ).toBe(true),
  },
  {
    fixture: "snapshot_not_implemented",
    // UI-coverage-gated: a valid call the emulator does not implement yet. Also
    // an expected outcome — must not red-error; still surfaced (info level). The
    // snapshot state stays at its default (the gated call mutated nothing).
    reflects: () => {
      expect(getMirror()["media.snapshot"]).not.toBe("PHOTO");
      expect(
        surfacedLines().some((t) =>
          /media_take_snapshot.*not implemented/.test(t),
        ),
      ).toBe(true);
    },
  },
];

// The reconcile state_change (present in EVERY fixture) carries the bmw_3series
// profile's read-only info, incl. the outside temperature. It flattens as
// `info.EXTERIOR_TEMPERATURE` (UPPER_SNAKE) — a renderer reading `info.exterior_temp`
// would silently never update the environment. Pin the canonical path here.
describe("reconcile environment (info.EXTERIOR_TEMPERATURE)", () => {
  it("reflects the outside temperature into the UI environment", () => {
    replay("climate_temp");
    expect(getMirror()["info.EXTERIOR_TEMPERATURE"]).toBe("57");
    expect(getState().environment.externalTemp).toBe(57);
  });
});

describe("bmwRenderer ⇄ emulator NDJSON golden fixtures", () => {
  beforeEach(() => {
    reset();
    clearConsole();
  });

  for (const { fixture, reflects } of SCENARIOS) {
    describe(fixture, () => {
      it("produces zero error-level console output", () => {
        replay(fixture);
        expect(errorLines()).toEqual([]);
      });

      it("reflects the command in the UI state", () => {
        replay(fixture);
        reflects();
      });
    });
  }
});
