// ---------------------------------------------------------------------------
// Mercedes (MBIS) multi-brand regression — the counterpart to the BMW golden replay in
// test/variants.integration.test.ts. Four parts:
//
//   1. Brand config loads/selects       — registry + brandStore (id lookup, ?brand pin,
//                                          content auto-detect, lock precedence, reset).
//   2. The MB NDJSON snapshot renders    — boot snapshot+reconcile ⇒ mercedes brand +
//                                          fully-classified mirror, zero error output.
//   3. Every MBIS outcome class handled  — applied/read/rejected/not_equipped/
//                                          not_implemented/cloud_deferred: correct
//                                          severity (error ONLY for rejected).
//   4. Golden corpus replay              — every Mercedes eval-gold signature grounded
//                                          through the real emulator (test/fixtures/
//                                          mercedes/, generated by tools/gen_mercedes_
//                                          golden.py) replayed through the mercedes
//                                          renderer path, asserting the shared (a)+(b)+(c)
//                                          contract from ./uiContract — NOTHING drops
//                                          silently, every emitted path mapped-or-ignored.
// ---------------------------------------------------------------------------
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect, beforeEach } from "vitest";
import { ingest, reset, getMirror } from "../src/agent/bmwRenderer";
import { getState } from "../src/state/vehicleState";
import { clearConsole } from "../src/agent/agentStore";
import { MERCEDES } from "../src/brands/mercedes";
import { BMW } from "../src/brands/bmw";
import { getBrand, detectBrand } from "../src/brands/registry";
import {
  getActiveBrand,
  setBrand,
  autoDetectBrand,
  resetBrand,
} from "../src/brands/brandStore";
import { makeContract, errorLines } from "./uiContract";

const contract = makeContract(MERCEDES);
const FIX = resolve(__dirname, "fixtures", "mercedes", "variants");

interface EmitterEvent {
  event: string;
  state?: Record<string, string>;
  changes?: { path: string; from?: string; to: string }[];
  intent?: string | null;
  result?: string;
  reason?: string | null;
}
interface VariantRecord {
  signature: string;
  intent: string;
  domain: string;
  events: EmitterEvent[];
}

/** The shared boot lines (snapshot + reconcile), parsed once. */
const BOOT: EmitterEvent[] = readFileSync(resolve(FIX, "_boot.ndjson"), "utf8")
  .split(/\r?\n/)
  .filter((l) => l.trim())
  .map((l) => JSON.parse(l) as EmitterEvent);

function loadVariants(): VariantRecord[] {
  const out: VariantRecord[] = [];
  for (const f of readdirSync(FIX).sort()) {
    if (!f.endsWith(".ndjson") || f === "_boot.ndjson") continue;
    for (const line of readFileSync(resolve(FIX, f), "utf8").split(/\r?\n/)) {
      if (line.trim()) out.push(JSON.parse(line) as VariantRecord);
    }
  }
  return out;
}
const VARIANTS = loadVariants();

/** All state paths a variant emits: boot snapshot keys + every state_change path. */
function emittedPaths(v: VariantRecord): Set<string> {
  const paths = new Set<string>();
  for (const e of [...BOOT, ...v.events]) {
    if (e.event === "snapshot" && e.state) Object.keys(e.state).forEach((p) => paths.add(p));
    if (e.event === "state_change" && e.changes) e.changes.forEach((c) => paths.add(c.path));
  }
  return paths;
}

// The full set of outcome classes the UI must handle (BMW's five + Mercedes' cloud class).
const KNOWN_OUTCOMES = new Set([
  "applied",
  "read",
  "rejected",
  "not_equipped",
  "not_implemented",
  "cloud_deferred",
]);

// ── 1. brand config loads / selects ─────────────────────────────────────────
describe("brand registry + selection", () => {
  beforeEach(() => resetBrand());

  it("resolves brand ids (case-insensitive) and rejects unknowns", () => {
    expect(getBrand("mercedes")).toBe(MERCEDES);
    expect(getBrand("Mercedes")).toBe(MERCEDES);
    expect(getBrand("bmw")).toBe(BMW);
    expect(getBrand("porsche")).toBeNull();
    expect(getBrand(null)).toBeNull();
  });

  it("defaults to BMW", () => {
    expect(getActiveBrand()).toBe(BMW);
  });

  it("setBrand pins (locks) the brand; unknown id is a no-op", () => {
    expect(setBrand("mercedes")).toBe(MERCEDES);
    expect(getActiveBrand()).toBe(MERCEDES);
    // Locked: auto-detect on BMW-looking state must NOT override the pin.
    autoDetectBrand({ "info.VIN": "WBA123" });
    expect(getActiveBrand()).toBe(MERCEDES);
    expect(setBrand("delorean")).toBeNull();
    expect(getActiveBrand()).toBe(MERCEDES);
  });

  it("content-detects Mercedes from the VIN prefix or MBIS zone keys", () => {
    expect(detectBrand({ "info.VIN": "W1KEQS0000A000000" })).toBe(MERCEDES);
    expect(detectBrand({ "climate.temperature.co-driver": "21" })).toBe(MERCEDES);
    expect(detectBrand({ "body.window.rear_left": "CLOSED" })).toBe(MERCEDES);
    expect(detectBrand({ "info.VIN": "WBA00000000000000" })).toBe(BMW);
  });

  it("autoDetectBrand switches an UNLOCKED brand and no-ops when locked", () => {
    resetBrand();
    autoDetectBrand({ "info.VIN": "W1KEQS0000A000000" });
    expect(getActiveBrand()).toBe(MERCEDES); // unlocked → switched
    setBrand("bmw"); // locks bmw
    autoDetectBrand({ "info.VIN": "W1KEQS0000A000000" });
    expect(getActiveBrand()).toBe(BMW); // locked → not overridden
  });
});

// ── 1b. multi-brand hardening regressions (code-review findings) ─────────────
describe("multi-brand hardening", () => {
  beforeEach(() => {
    reset();
    resetBrand();
    clearConsole();
  });

  it("a ?brand= pin SURVIVES reset() (reset must not clobber the brand)", () => {
    setBrand("mercedes"); // simulate ?brand=mercedes (locked)
    reset(); // the documented 'before reconnecting to a fresh emulator' action
    expect(getActiveBrand()).toBe(MERCEDES);
  });

  it("auto-detect is STICKY — a brand-neutral boot snapshot does not revert Mercedes to BMW", () => {
    autoDetectBrand({ "info.VIN": "W1KEQS0000A000000" }); // detect Mercedes (unpinned)
    expect(getActiveBrand()).toBe(MERCEDES);
    // A reconnect delivers the brand-neutral engine boot snapshot (uppercase, WBA VIN).
    autoDetectBrand({ "info.VIN": "WBA00000000000000", "climate.temperature.DRIVER": "21" });
    expect(getActiveBrand()).toBe(MERCEDES); // must NOT flip back to BMW
  });

  it("live lowercase MBIS temp is not shadowed by the stale uppercase boot key", () => {
    setBrand("mercedes");
    // Mirror carries BOTH the uppercase boot default (21°C) and a live lowercase MBIS
    // setpoint (24°C). The rig must reflect the live value (24°C ≈ 75°F), not 21°C (70°F).
    ingest({
      v: 2,
      event: "snapshot",
      state: { "climate.temperature.DRIVER": "21", "climate.temperature.driver": "24" },
    });
    expect(getState().temperature).toBe(75);
  });
});

// ── 2. the MB NDJSON snapshot renders ───────────────────────────────────────
describe("Mercedes boot snapshot renders", () => {
  beforeEach(() => {
    reset();
    resetBrand(); // reset() no longer touches the brand; start unpinned so auto-detect runs
    clearConsole();
  });

  it("auto-detects Mercedes from the boot reconcile (no ?brand= needed)", () => {
    for (const e of BOOT) ingest(e);
    expect(getActiveBrand()).toBe(MERCEDES);
    // The boot reconcile carries the MBIS EQS VIN and lowercase zone keys.
    expect(getMirror()["info.VIN"]).toBe("W1KEQS0000A000000");
    expect(getMirror()["climate.temperature.driver"]).toBeDefined();
  });

  it("renders the full boot with zero error output and every path classified", () => {
    setBrand("mercedes"); // pin, as the demo does via ?brand=mercedes
    for (const e of BOOT) ingest(e);
    expect(errorLines()).toEqual([]);
    const paths = new Set<string>();
    for (const e of BOOT) {
      if (e.event === "snapshot" && e.state) Object.keys(e.state).forEach((p) => paths.add(p));
      if (e.event === "state_change" && e.changes) e.changes.forEach((c) => paths.add(c.path));
    }
    const unclassified = [...paths].filter((p) => contract.classify(p) === "unclassified");
    expect(unclassified, `unclassified: ${unclassified.join(", ")}`).toEqual([]);
    // A mapped path drove the rig: metric setpoint (21°C) → 70°F.
    expect(getState().temperature).toBe(70);
  });
});

// ── 3. every MBIS outcome class is handled ──────────────────────────────────
describe("MBIS outcome classes", () => {
  beforeEach(() => {
    reset();
    setBrand("mercedes");
    clearConsole();
  });

  const cases: { result: string; error: boolean }[] = [
    { result: "applied", error: false },
    { result: "read", error: false },
    { result: "not_equipped", error: false },
    { result: "not_implemented", error: false },
    { result: "cloud_deferred", error: false },
    { result: "rejected", error: true },
  ];

  for (const c of cases) {
    it(`${c.result} → ${c.error ? "error" : "non-error"} affordance, never dropped`, () => {
      ingest({ v: 2, event: "outcome", intent: "carFunction.set-carFunction.AC", result: c.result, reason: null });
      // Every class is known — no outcome is silently ignored.
      expect(KNOWN_OUTCOMES.has(c.result)).toBe(true);
      if (c.error) expect(errorLines().length).toBeGreaterThan(0);
      else expect(errorLines()).toEqual([]);
    });
  }
});

// ── 4. golden corpus replay ─────────────────────────────────────────────────
describe("Mercedes eval-gold corpus replay", () => {
  it("fixtures were generated (non-trivial corpus across MBIS domains)", () => {
    expect(existsSync(FIX)).toBe(true);
    expect(VARIANTS.length).toBeGreaterThanOrEqual(200);
    expect(new Set(VARIANTS.map((v) => v.domain)).size).toBeGreaterThanOrEqual(6);
  });

  it("every emitted outcome is a KNOWN class (no unhandled outcome)", () => {
    for (const v of VARIANTS) {
      for (const e of v.events) {
        if (e.event === "outcome") {
          expect(KNOWN_OUTCOMES.has(String(e.result)), `${v.signature} → ${e.result}`).toBe(true);
        }
      }
    }
  });

  it("exercises the grounded outcome classes (applied/read/cloud_deferred/rejected)", () => {
    // Since the emulator grounds ALL valid MBIS intents, the corpus no longer contains
    // `not_implemented` (every valid intent now Applies/Reads); `rejected` remains for
    // the version-skew eval golds the 0608 collection doesn't accept. The renderer still
    // HANDLES not_implemented if it ever appears (see the outcome-class unit suite); this
    // corpus assertion tracks what the ground-all emulator actually emits.
    const seen = new Set<string>();
    for (const v of VARIANTS)
      for (const e of v.events) if (e.event === "outcome") seen.add(String(e.result));
    for (const cls of ["applied", "read", "cloud_deferred", "rejected"]) expect(seen).toContain(cls);
    expect(seen).not.toContain("not_implemented");
  });

  beforeEach(() => {
    reset();
    setBrand("mercedes"); // the demo pins mercedes via ?brand=mercedes
    clearConsole();
  });

  for (const v of VARIANTS) {
    it(`${v.signature}`, () => {
      for (const e of BOOT) ingest(e);
      for (const e of v.events) ingest(e);
      const m = getMirror();
      const paths = emittedPaths(v);
      const rejected = v.events.some((e) => e.event === "outcome" && e.result === "rejected");
      // Asserts (a) zero error output for a non-rejected turn, (b) every mapped path
      // reflected in getState()/getMusic(), (c) every emitted path mapped-or-ignored.
      contract.assertContract(m, paths, { rejected });
    });
  }
});
